{MineForm.LoadResource}

{Шрифты}
   MineForm.LoadResource(TmpPrefix+'Calibri Light-Regular-10pt.zfi','Calibri Light-Regular-10');
   MineForm.LoadResource(TmpPrefix+'Calibri Light-Regular-20pt.zfi','Calibri Light-Regular-20');
   MineForm.LoadResource(TmpPrefix+'Calibri Light-Regular-36pt.zfi','Calibri Light-Regular-36');
{Базовые картинки}
   MineForm.LoadResource(TmpPrefix+'main.png','Логотип');
   MineForm.LoadResource(TmpPrefix+'ErrorImg.png','for error');
   MineForm.LoadResource(TmpPrefix+'blueback.png', 'wallpaper');
   MineForm.LoadResource(TmpPrefix+'simplebutton.png', 'Кнопка');
   MineForm.LoadResource(TmpPrefix+'fraimwallpaper.png', 'Обои фрейма');
   MineForm.LoadResource(TmpPrefix+'connor_btn.png', 'Угловая кнопка');
   MineForm.LoadResource(TmpPrefix+'swichbutton.png', 'Чекбокс');
   MineForm.LoadResource(TmpPrefix+'bevelpanel.png', 'Панелька');
   MineForm.LoadResource(TmpPrefix+'bevelpanelec.png', 'Панелька пуст');
   MineForm.LoadResource(TmpPrefix+'cursor.png', 'Cursor');
{Спрайты}
   MineForm.LoadResource(TmpPrefix+'PersonSteps.png', 'Шагающий стрелок');
   MineForm.LoadResource(TmpPrefix+'leafs.png', 'Листочек');
{Тайлы}
   MineForm.LoadResource(TmpPrefix+'tile_floor1.png', 'пол1');
   MineForm.LoadResource(TmpPrefix+'tile_floor2.png', 'пол2');
   MineForm.LoadResource(TmpPrefix+'tile_floor3.png', 'пол3');
   MineForm.LoadResource(TmpPrefix+'tile_floor4.png', 'пол4');
   MineForm.LoadResource(TmpPrefix+'m_a_tilefloor05.png', 'пол11');
   MineForm.LoadResource(TmpPrefix+'m_m_metaltiles02.png', 'пол9');
   MineForm.LoadResource(TmpPrefix+'m_m_platform01.png', 'пол10');
   MineForm.LoadResource(TmpPrefix+'m_m_platform03.png', 'пол5');
   MineForm.LoadResource(TmpPrefix+'m_m_platform04.png', 'пол6');
   MineForm.LoadResource(TmpPrefix+'plat_anim.png', 'пол7');
   MineForm.LoadResource(TmpPrefix+'BorderIndicatorComp64.png', 'край со стрелкой');
   MineForm.LoadResource(TmpPrefix+'m_a_tilefloor01.png', 'пол8');
   MineForm.LoadResource(TmpPrefix+'bullet.png', 'пулька');
{Разобранный спрайт}
   MineForm.LoadResource(TmpPrefix+'helmet.png', 'спрайт шлем');
   MineForm.LoadResource(TmpPrefix+'arrow_head.png', 'спрайт стрелка на шлем');
   MineForm.LoadResource(TmpPrefix+'right_shoulder.png', 'спрайт правое плечо');
   MineForm.LoadResource(TmpPrefix+'left_shoulder.png', 'спрайт левое плечо');
   MineForm.LoadResource(TmpPrefix+'left_hand.png', 'спрайт левая рука');
   MineForm.LoadResource(TmpPrefix+'right_hand.png', 'спрайт правая рука');
   MineForm.LoadResource(TmpPrefix+'backpack.png', 'спрайт рюкзак');
   MineForm.LoadResource(TmpPrefix+'star.png', 'спрайт звездочка');
   MineForm.LoadResource(TmpPrefix+'left_foot.png', 'спрайт левая нога');
   MineForm.LoadResource(TmpPrefix+'right_foot.png', 'спрайт правая нога');
   MineForm.LoadResource(TmpPrefix+'riffle.png', 'винтовка');

   MineForm.LoadResource(TmpPrefix+'f.cls', 'пример');

