CoolSprite
Frame=0
StartFrame=0
EndFrame=4
FPS=24
Sprite
Name=left_foot
ID=1
Texture=left_foot.png
X=-46
Y=24
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
14
30
4
0 0
27 0
27 59
0 59
PosKeys=3
0 2 -46 24
1 2 -41 8
3 2 -41 -6
AngKeys=2
0 2 0
2 2 -4.04
Sprite
Name=right_foot
ID=2
Texture=right_foot.png
X=50
Y=-15
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
14
30
4
0 0
27 0
27 59
0 59
PosKeys=4
0 2 50 -15
1 2 51 -2
2 2 55 9
3 2 58 22
AngKeys=3
0 2 0
2 2 -0.31
3 2 -1.1
Sprite
Name=left_hand
ID=3
Texture=left_hand.png
X=-62
Y=-11
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
16
65
4
0 0
33 0
33 79
0 79
PosKeys=4
0 2 -62 -11
1 2 -69 1
2 2 -70 7
3 2 -66 19
Sprite
Name=right_hand
ID=4
Texture=right_hand.png
X=89
Y=2
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
17
67
4
0 0
33 0
33 79
0 79
PosKeys=3
0 2 89 2
1 2 88 -10
2 2 85 -15
AngKeys=2
0 2 0
3 2 1.08
Sprite
Name=backpack
ID=5
Texture=backpack.png
X=5
Y=42
Angle=6.03
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
46
21
4
0 0
94 0
94 45
0 45
AngKeys=2
0 2 6.03
3 2 -10.36
Sprite
Name=left_shoulder
ID=6
Texture=left_shoulder.png
X=46
Y=9
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
16
32
4
0 0
72 0
72 63
0 63
PosKeys=3
0 2 46 9
1 2 46 4
3 2 45 0
AngKeys=2
0 2 0
3 2 -7.71
Sprite
Name=right_shoulder
ID=7
Texture=right_shoulder.png
X=-33
Y=7
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
53
33
4
0 0
72 0
72 63
0 63
PosKeys=3
0 2 -33 7
1 2 -32 14
3 2 -30 21
AngKeys=3
0 2 0
1 2 -8.1
3 2 -15.66
Sprite
Name=helmet
ID=8
Texture=helmet.png
X=0
Y=0
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
38
39
4
0 0
75 0
75 78
0 78
Sprite
Name=star
ID=10
Texture=star.png
X=-68
Y=3
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
11
10
4
0 0
22 0
22 21
0 21
PosKeys=3
0 2 -68 3
1 2 -68 17
3 2 -66 26
AngKeys=3
0 2 0
1 2 -6.34
3 2 2.63
Sprite
Name=star
ID=11
Texture=star.png
X=87
Y=8
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
12
12
4
0 0
22 0
22 21
0 21
PosKeys=3
0 2 87 8
1 2 86 2
3 2 85 -6
Sprite
Name=riffle
ID=12
Texture=riffle.png
X=-5
Y=-64
Angle=10.18
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
124
10
4
0 0
249 0
249 20
0 20
PosKeys=2
0 2 -5 -64
3 2 2 -51
AngKeys=4
0 2 10.18
1 2 -4.18
2 2 -7.15
3 2 -14.81
Sprite
Name=arrow_head
ID=9
Texture=arrow_head.png
X=0
Y=0
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
18
30
4
0 0
35 0
35 59
0 59
