CoolSprite
Frame=0
StartFrame=0
EndFrame=10
FPS=10
Sprite
Name=spider_big_leg_bone
ID=1
Texture=spider_big_leg_bone.png
X=18.5
Y=-14.5
Angle=-18.9
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=14
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
10.82
40.99
4
0 0
56 0
56 51
0 51
AngKeys=9
0 2 -18.9
1 2 -24.54
2 2 -39.14
3 2 -27.96
4 2 -20.99
5 2 -20.17
6 2 -29.26
7 2 -25
10 2 -20.7
Sprite
Name=spider_big_leg_bone
ID=2
Texture=spider_big_leg_bone.png
X=24.58
Y=12
Angle=35.41
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=14
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
11.24
40.29
4
0 0
56 0
56 51
0 51
PosKeys=1
0 2 24.58 12
AngKeys=10
0 2 35.41
1 2 46.23
2 2 56.02
3 2 49.64
4 2 38.69
5 2 23.75
6 2 12.06
7 2 17.7
8 2 25.13
9 2 33.33
Sprite
Name=spider_big_leg_bone
ID=3
Texture=spider_big_leg_bone.png
X=21.74
Y=42.5
Angle=81.41
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=14
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
12.09
38.81
4
0 0
56 0
56 51
0 51
PosKeys=2
0 2 21.74 42.5
1 2 26.77 50.45
AngKeys=10
0 2 81.41
1 2 63.12
2 2 51.25
3 2 58.38
4 2 80.18
5 2 91.52
6 2 83.96
8 2 78.15
9 2 79.94
10 2 74.49
Sprite
Name=spider_big_leg_bone
ID=4
Texture=spider_big_leg_bone.png
X=-20.5
Y=-15
Angle=275.89
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=14
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
11.43
39.67
4
0 0
56 0
56 51
0 51
AngKeys=9
0 2 275.89
1 2 284.91
2 2 276.05
3 2 285.96
4 2 284.11
5 2 286.22
6 2 296.89
7 2 288.89
10 2 276.87
Sprite
Name=spider_big_leg_bone
ID=5
Texture=spider_big_leg_bone.png
X=-24.4
Y=13
Angle=221.3
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=14
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
11.86
39.88
4
0 0
56 0
56 51
0 51
PosKeys=2
0 2 -24.4 13
1 2 -21.49 4.97
AngKeys=10
0 2 221.3
1 2 230.67
2 2 239.12
3 2 217.41
4 2 206.74
5 2 195.51
6 2 189.41
7 2 199.27
8 2 205.8
9 2 212.71
Sprite
Name=spider_rside_leg_bone
ID=20
Texture=spider_rside_leg_bone.png
X=-11.89
Y=4.82
Angle=308.52
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=10
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
21
29.5
4
0 0
33 0
33 41
0 41
AngKeys=3
0 2 308.52
3 2 311.78
6 2 311.09
Sprite
Name=spider_big_leg_bone
ID=6
Texture=spider_big_leg_bone.png
X=-23.76
Y=42.5
Angle=176.37
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=14
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
11.01
39.4
4
0 0
56 0
56 51
0 51
PosKeys=2
0 2 -23.76 42.5
1 2 -18.74 49.45
AngKeys=11
0 2 176.37
1 2 177.4
2 2 165.5
3 2 193.74
4 2 202.88
5 2 213.17
6 2 215.88
7 2 210.96
8 2 203.74
9 2 193.94
10 2 188.84
Sprite
Name=spider_leg_joint
ID=7
Texture=spider_leg_joint.png
X=44.18
Y=-36.49
Angle=-22.07
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=1
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
8.5
9
4
0 0
17 0
17 17
0 17
AngKeys=6
0 2 -22.07
2 2 -9.71
4 2 -5.17
5 2 9.01
8 2 -7.15
10 2 -19.26
Sprite
Name=spider_leg_joint
ID=8
Texture=spider_leg_joint.png
X=41.8
Y=-35.03
Angle=298.22
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=2
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
8
8
4
0 0
17 0
17 17
0 17
AngKeys=5
0 2 298.22
1 2 290.15
3 2 297.88
4 2 288.29
10 2 301.07
Sprite
Name=spider_leg_joint
ID=9
Texture=spider_leg_joint.png
X=41.42
Y=-33.39
Angle=253.4
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=3
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
8
8
4
0 0
17 0
17 17
0 17
AngKeys=5
0 2 253.4
1 2 248.86
3 2 267.99
5 2 243.62
6 2 250.08
Sprite
Name=spider_leg_joint
ID=10
Texture=spider_leg_joint.png
X=43.96
Y=-33.61
Angle=221.34
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=6
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
8
8
4
0 0
17 0
17 17
0 17
AngKeys=10
0 2 221.34
1 2 215.55
2 2 219.07
3 2 186.85
4 2 193.82
5 2 181.1
6 2 162.98
7 2 184.18
8 2 197.97
10 2 202.14
Sprite
Name=spider_leg_joint
ID=11
Texture=spider_leg_joint.png
X=42.98
Y=-34.24
Angle=164.95
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=5
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
8
8
4
0 0
17 0
17 17
0 17
AngKeys=4
0 2 164.95
1 2 177.94
3 2 177.04
4 2 168.01
Sprite
Name=spider_leg_joint
ID=12
Texture=spider_leg_joint.png
X=43.52
Y=-35.1
Angle=120.91
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=4
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
8
8
4
0 0
17 0
17 17
0 17
AngKeys=5
0 2 120.91
2 2 129.98
5 2 87.63
8 2 102.92
10 2 111.05
Sprite
Name=spider_front_leg_bone
ID=13
Texture=spider_front_leg_bone.png
X=0.5
Y=-16
Angle=-0.29
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=7
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
9.5
45.5
4
0 0
22 0
22 57
0 57
Sprite
Name=spider_body
ID=14
Texture=spider_body.png
X=-1.5
Y=-1
Angle=0.62
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
29.5
27.5
4
0 0
61 0
61 106
0 106
PosKeys=1
0 2 -1.5 -1
AngKeys=2
0 2 0.62
3 2 0.29
Sprite
Name=spider_rfront_leg_bone
ID=16
Texture=spider_rfront_leg_bone.png
X=-1
Y=-14
Angle=0
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=12
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
11.5
45.5
4
0 0
22 0
22 57
0 57
Sprite
Name=spider_side_leg_bone
ID=17
Texture=spider_side_leg_bone.png
X=12.5
Y=-5.5
Angle=0.87
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=8
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
12
29.5
4
0 0
33 0
33 41
0 41
AngKeys=1
0 2 0.87
Sprite
Name=spider_side_leg_bone
ID=18
Texture=spider_side_leg_bone.png
X=14.5
Y=5
Angle=43.84
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=9
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
13.5
29.5
4
0 0
33 0
33 41
0 41
AngKeys=2
0 2 43.84
2 2 43.26
Sprite
Name=spider_rside_leg_bone
ID=19
Texture=spider_rside_leg_bone.png
X=-10.93
Y=-6.55
Angle=358.16
ScaleX=1
ScaleY=1
FlipX=FALSE
FlipY=FALSE
Visible=TRUE
InheritVis=FALSE
ParentID=11
Frame=1
FPS=24
Animated=FALSE
Speed=1
Frames=1
21
29.5
4
0 0
33 0
33 41
0 41
AngKeys=1
0 2 358.16
